config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get "/dashboard", to: "dashboard#index"

  devise_for :users, path: "",
  path_names: {sign_in: "login", sign_up: "signup", sign_out: "logout"}

  resources :users, only: [:show, :edit, :update] do
    member do
      post "follow", to: "followings#create"
      delete "unfollow", to: "followings#destroy"
    end
    resources :liked_genres, only: [:create]
  end

  resources :ownerships, only: [:new, :create, :update, :destroy] do
    resources :transfers, only: [:create]
  end
  resources :transfers, only: [:destroy]
  put "/transfers/:id/accept", to: "transfers#accept"

  resources :books, only: [:index, :show, :create] do
    resources :recommendations, only: [:new, :create, :destroy]
  end

  post "/recommendations/:id/thank", to: "thanks#create"

  resources :notifications, only: [:index]
  put "/notifications/:id/mark-read", to: "notifications#mark_read"

  resources :events, only: [:index]

  get "/search", to: "search#search"

  namespace :api do
    namespace :v1 do
      get "books", to: "books#index"
      get "books/search", to: "books#search"
      get "books/complex_search", to: "books#search_complex"
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @users = User.search_by_username(params[:term])
    @books = BooksElasticsearch.new.search(params[:term])
  end
end

app/views/search/search.html.erb
<div class="row margin-top">
  <div class="col-md-5 col-md-offset-1">

    <% if @users.any? %>
      <% @users.each do |user| %>
        <div class="card search--card">

          <div class="card--thumbnail">
            <%= image_tag user.avatar.url(:square), class: "img-responsive center-block" %>
          </div>

          <div>
            <h3><%= link_to "#{user.username}", user_path(user) %></h3>
            <p>
              <span aria-hidden="true" class="glyphicon glyphicon-map-marker"></span>
              <%= user.location %>
            </p>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="lead text-center">
        No users found.
      </p>
    <% end %>

  </div>

  <div class="col-md-5">
    <% if @books.any? %>
      <% @books.each do |book| %>
        <div class="card search--card">

          <div class="card--thumbnail">
            <%= image_tag book.cover.url(:medium), class: "img-responsive center-block" %>
          </div>

          <div>
            <h3><%= link_to book.title.titleize, book_path(book) %></h3>
            <p class="lead">
              <%= book.author %>
            </p>
            <p>
              <%= pluralize(book.ownerships.count, "user") %> offer this book.
            </p>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="lead text-center">
        No books found.
      </p>
    <% end %>

  </div>
</div>