config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get "/dashboard", to: "dashboard#index"

  devise_for :users, path: "",
  path_names: {sign_in: "login", sign_up: "signup", sign_out: "logout"}

  resources :users, only: [:show, :edit, :update] do
    member do
      post "follow", to: "followings#create"
      delete "unfollow", to: "followings#destroy"
    end
    resources :liked_genres, only: [:create]
  end

  resources :ownerships, only: [:new, :create, :update, :destroy] do
    resources :transfers, only: [:create]
  end
  resources :transfers, only: [:destroy]
  put "/transfers/:id/accept", to: "transfers#accept"

  resources :books, only: [:index, :show, :create] do
    resources :recommendations, only: [:new, :create, :destroy]
  end

  post "/recommendations/:id/thank", to: "thanks#create"

  resources :notifications, only: [:index]
  put "/notifications/:id/mark-read", to: "notifications#mark_read"

  resources :events, only: [:index]

  get "/search", to: "search#search"

  namespace :api do
    namespace :v1 do
      get "books", to: "books#index"
      get "books/search", to: "books#search"
      get "books/complex_search", to: "books#search_complex"
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :ownerships
  has_many :users, through: :ownerships

  has_many :recommendations

  belongs_to :genre

  has_attached_file :cover, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '500x500>'
  }
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\z/

  validates_presence_of :title, :author

  after_commit :index_elasticsearch
  before_destroy :destroy_elasticsearch

  def self.search_by_title(title)
    where("UPPER(title) LIKE ?", "%#{title.upcase}%")
  end

  def self.search_offered_by_title(title)
    joins(:ownerships).where("UPPER(title) LIKE ?", "%#{title.upcase}%").where("ownerships.to_give_away is true OR ownerships.to_exchange is true")
  end

  def offerings
    ownerships.where("to_give_away is true OR to_exchange is true")
  end

  def offerings_count
    ownerships.where("to_give_away is true OR to_exchange is true").count
  end

  def valoration
    recommendations.inject(0) do |amount, recommendation|
      amount + (recommendation.valoration * (recommendation.user.reputation.to_f / 1000))
    end
  end

  private

  def index_elasticsearch
    BooksElasticsearch.new.index(self)
  end

  def destroy_elasticsearch
    BooksElasticsearch.new.destroy(self)
  end

end

app/controllers/api/v1/books_controller.rb
module Api
  module V1
    class BooksController < ApplicationController
      def search
        limit = params[:limit] || 10
        books = Book.search_by_title(params[:term]).limit(limit)

        results = books.map do |book|
          {}.tap do |book_hash|
            book_hash[:id] = book.id
            book_hash[:title] = book.title
            book_hash[:author] = book.author
            book_hash[:genre] = book.genre
            book_hash[:cover_url] = book.cover.url
          end
        end

        render status: 200, json: results
      end

      def search_complex
        limit = params[:limit] || 10
        books = BooksElasticsearch.new.search(params[:term], limit)

        results = books.map do |book|
          {}.tap do |book_hash|
            book_hash[:id] = book.id
            book_hash[:title] = book.title
            book_hash[:author] = book.author
            book_hash[:genre] = book.genre
            book_hash[:cover_url] = book.cover.url
          end
        end

        render status: 200, json: results
      end

      def index
        books = Book.all

        results = books.map do |book|
          {}.tap do |book_hash|
            book_hash[:id] = book.id
            book_hash[:title] = book.title
            book_hash[:author] = book.author
            book_hash[:genre] = book.genre
            book_hash[:cover_url] = book.cover.url
          end
        end
        render status: 200, json: results
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:search]

  def index
    @books = Book.all
    render status: 200, json: @books
  end

  def show
    @book = Book.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render status: 200, json: @book }
    end
  end

  def create
    Book.create(book_params)
    redirect_to new_ownership_path
  end

  def search
    books = Book.search_offered_by_title(params[:term])
    render status: 200, json: books
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :cover, :genre_id)
  end
end

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="card">
      <div class="row">
        <div class="col-md-4">
          <%= image_tag @book.cover.url(:medium), class: "img-responsive center-block" %>
        </div>
        <div class="col-md-6 col-md-offset-1">
          <h1><%= @book.title.titleize %></h1>
          <p class="lead">
            <%= @book.author %>
          </p>
          <p>
            <%= pluralize(@book.offerings_count, "user") %> offer this book.
          </p>
          <p>
            <span class="label label-default"><%= @book.genre.name %></span>
          </p>
          <p>
            <% if @book.valoration %>
              Rating: <%= @book.valoration.round(2) %>
            <% else %>
              No ratings yet.
            <% end %>
          </p>
          <div class="center-block">
            <%= link_to "Recommend it", new_book_recommendation_path(@book), class: "center-block btn btn-primary" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="row margin-top">
  <div class="col-md-5 col-md-offset-1">
    <%= render "ownerships/ownership_users_list", ownerships: @book.offerings %>
  </div>

  <div class="col-md-5">
    <%= render "recommendations/recommendations_comments_list", recommendations: @book.recommendations %>
  </div>
</div>