config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get "/dashboard", to: "dashboard#index"

  devise_for :users, path: "",
  path_names: {sign_in: "login", sign_up: "signup", sign_out: "logout"}

  resources :users, only: [:show, :edit, :update] do
    member do
      post "follow", to: "followings#create"
      delete "unfollow", to: "followings#destroy"
    end
    resources :liked_genres, only: [:create]
  end

  resources :ownerships, only: [:new, :create, :update, :destroy] do
    resources :transfers, only: [:create]
  end
  resources :transfers, only: [:destroy]
  put "/transfers/:id/accept", to: "transfers#accept"

  resources :books, only: [:index, :show, :create] do
    resources :recommendations, only: [:new, :create, :destroy]
  end

  post "/recommendations/:id/thank", to: "thanks#create"

  resources :notifications, only: [:index]
  put "/notifications/:id/mark-read", to: "notifications#mark_read"

  resources :events, only: [:index]

  get "/search", to: "search#search"

  namespace :api do
    namespace :v1 do
      get "books", to: "books#index"
      get "books/search", to: "books#search"
      get "books/complex_search", to: "books#search_complex"
    end
  end

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :ownership
  belongs_to :user

  def accept!
    update_attributes(accepted: true)
    transfer_book_ownership
  end

  private

  def transfer_book_ownership
    user.ownerships.create(book_id: ownership.book.id)
    ownership.destroy
  end

end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def create
    ownership_to_transfer = Ownership.find(params[:ownership_id])
    transfer_request = current_user.request_transfer(ownership_to_transfer)
    TransferRequestMailer.transfer_request_received_mail(transfer_request.ownership.user, transfer_request).deliver_later
    # redirect_to "/"
    render status: 201, json: transfer_request
  end

  def accept
    transfer_to_accept = current_user.received_transfers.find(params[:id])
    transfer_to_accept.accept!
    redirect_to user_path(current_user)
  end

  def destroy
    current_user.reject_transfer_request(params[:id])
    redirect_to notifications_path
  end
end

app/views/transfers/_transfer_requests_list.html.erb
<% if transfer_requests.any? %>
  <% transfer_requests.each do |request| %>
      <div class="card">
        <p>
          <%= link_to request.user.username, user_path(request.user) %>
          requested you to transfer
          <%= link_to request.ownership.book.title, book_path(request.ownership.book) %>
        </p>

        <p>
          <%= link_to "Email this user", "mailto:#{request.user.email}" %>
        </p>

        <%= form_tag "/transfers/#{request.id}/accept", method: "put" do %>
          <%= submit_tag "Accept" , class: "btn btn-primary" %>
        <% end %>
        <%= form_tag transfer_path(request), method: "delete" do %>
          <%= submit_tag "Reject" , class: "btn btn-danger" %>
        <% end %>
      </div>
  <% end %>

<% else %>
  <p class="lead text-center">
    No pending transfer requests
  </p>
<% end %>

app/views/transfers/index.html.erb
<% @transfer_requests.each do |request| %>
  <div class="row">
    <div class="card col-md-6 col-md-offset-3">
      <%= link_to request.user.username, user_path(request.user) %>
      requested you to transfer
      <%= link_to request.ownership.book.title, book_path(request.ownership.book) %>

      <%= form_tag "/transfers/#{request.id}/accept", method: "put" do %>
        <%= submit_tag "Accept" , class: "btn btn-primary" %>
      <% end %>
      <%= form_tag transfer_path(request), method: "delete" do %>
        <%= submit_tag "Reject" , class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
<% end %>