config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get "/dashboard", to: "dashboard#index"

  devise_for :users, path: "",
  path_names: {sign_in: "login", sign_up: "signup", sign_out: "logout"}

  resources :users, only: [:show, :edit, :update] do
    member do
      post "follow", to: "followings#create"
      delete "unfollow", to: "followings#destroy"
    end
    resources :liked_genres, only: [:create]
  end

  resources :ownerships, only: [:new, :create, :update, :destroy] do
    resources :transfers, only: [:create]
  end
  resources :transfers, only: [:destroy]
  put "/transfers/:id/accept", to: "transfers#accept"

  resources :books, only: [:index, :show, :create] do
    resources :recommendations, only: [:new, :create, :destroy]
  end

  post "/recommendations/:id/thank", to: "thanks#create"

  resources :notifications, only: [:index]
  put "/notifications/:id/mark-read", to: "notifications#mark_read"

  resources :events, only: [:index]

  get "/search", to: "search#search"

  namespace :api do
    namespace :v1 do
      get "books", to: "books#index"
      get "books/search", to: "books#search"
      get "books/complex_search", to: "books#search_complex"
    end
  end

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <% if key == "alert" %>
    <% key = "danger" %>
  <% else %>
    <% key = "info" %>
  <% end %>
  <%= content_tag :div, value, class: "text-center alert alert-#{key}" %>
<% end %>

app/views/layouts/_recommendation_likes.html.erb
<div class="thank-container">
    <% if current_user.id != recommendation.user.id && !current_user.thanked?(recommendation) %>
      <button data-id="<%= recommendation.id %>" type="button" class="btn btn-primary pull-right btn-sm thank-recommendation" name="button">Thank!</button>
    <% else %>
      <button data-id="<%= recommendation.id %>" type="button" class="btn btn-primary pull-right btn-sm thank-recommendation btn-successful" disabled="true" name="button"><%= pluralize(recommendation.thanks.count, "thank") %></button>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Changebook</title>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1" name="viewport">
  </head>
  <body>

      <div class="wrap">
    <% if current_user %>

        <div class="container-fluid">
          <nav class="navbar navbar-primary navbar--custom navbar-fixed-top">
            <div class="container-fluid">
              <div class="navbar-header">
                <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <% if current_user %>
                <%= link_to "ChangeBook!", dashboard_path, class: "navbar-brand" %>
                <% else %>
                <a class="navbar-brand" href="/">
                  ChangeBook!
                </a>
                <% end %>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right">
                  <% if current_user %>
                  <form action="<%= search_path %>" class="navbar-form navbar-left" method="GET">
                    <div class="form-group">
                      <input class="form-control" id="user-search" name="term" placeholder="Search..." type="text">
                    </div>
                  </form>

                  <li>
                    <%= link_to "Offer book", new_ownership_path %>
                  </li>

                  <li>
                    <% badge = "<span class='badge'>#{current_user.received_transfers.count + current_user.unread_notifications.count}</span>" if current_user.received_transfers.any? || current_user.unread_notifications.any? %>
                    <%= link_to raw("Notifications #{badge}"), notifications_path %>
                  </li>

                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
                      <%= current_user.username %>
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to "Profile", user_path(current_user) %>
                      </li>
                      <li>
                        <%= link_to "Edit profile", edit_user_path(current_user) %>
                      </li>
                      <li>
                        <%= link_to "Edit account", edit_registration_path(current_user) %>
                      </li>
                      <li class="divider" role="separator"></li>
                      <li>
                        <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
                      </li>
                    </ul>
                  </li>
                  <% end %>
                </ul>

              </div>
            </div>
          </nav>
        </div>
    <% end %>

        <div class="container app-content">
          <%= render 'layouts/flashes'  %>
          <%= yield %>
        </div>

        <div class="push"></div>
      </div>

      <div class="footer">
        <div class="container">
          <div class="row">
            <p class="text-center">Welcome to ChangeBook! by uesteibar @ ironhack. 2015.</p>
          </div>
        </div>
      </div>
  </body>
</html>